/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/login` | `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/signup` | `/signup/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Calls/page` | `/Calls/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Chats/page` | `/Chats/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Status/page` | `/Status/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/settings/page` | `/settings/page`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login/login` | `/login/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/signup` | `/signup/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Calls/page` | `/Calls/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Chats/page` | `/Chats/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Status/page` | `/Status/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/settings/page` | `/settings/page`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login/login${`?${string}` | `#${string}` | ''}` | `/login/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/signup${`?${string}` | `#${string}` | ''}` | `/signup/signup${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/Calls/page${`?${string}` | `#${string}` | ''}` | `/Calls/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/Chats/page${`?${string}` | `#${string}` | ''}` | `/Chats/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/Status/page${`?${string}` | `#${string}` | ''}` | `/Status/page${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/settings/page${`?${string}` | `#${string}` | ''}` | `/settings/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/login` | `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/signup` | `/signup/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Calls/page` | `/Calls/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Chats/page` | `/Chats/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/Status/page` | `/Status/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/settings/page` | `/settings/page`; params?: Router.UnknownInputParams; };
    }
  }
}
